name: Build and push DinD images to GHCR

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # weekly: Mondays 6:03 am, UTC (replaces CircleCI 'weekly' buildx job)
  schedule:
    - cron: "3 6 * * 1"

jobs:
  build-and-push-image:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/dind-images.yml
    with:
      version: "latest"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
